### ISSUE TITLE
Enable Spellcheck to notes

### ISSUE THREAD

**Issue by Kiyozz** [jonathontoon/manifest#122]
`<textareas>` has attribute `spellcheck` to `false` that cause MacOS text replacement to not works.

#### Safari
Given a replacement of `tt` to `tutu`
When I type `tt` plus a space
Then I should see `tutu`

#### Chrome
Given a replacement of `tt` to `tutu`
When I type `tt` plus a space
Then I should see `tutu`

#### Safari
I see `tt` -> no replacement cause of `spellcheck="false"`

#### Chrome
I see `tutu` -> Chrome ignores `spellcheck` attribute or works differently

## Possible Solution

Remove spellcheck attribute. Why for a note app, you disable spellcheck?

## Context

Trying to write notes with my favorite text replacements

## Your Environment

* Operating System and version:

MacOS 10.15.2 on Safari 13.0.4
MacOS 10.15.2 on Chrome 80

**Comment by jonathontoon** [comment]
@Kiyozz thanks for reporting! Originally I disabled it due to text that was non actual vocabulary causing a lot of red underlines (urls, markdown, code etc), which for some was equally as annoying.

If it's impacting usability on macOS I'm more than happy to approve a PR to add it back in. Right now I don't have any access to Apple devices so I have no ability to test out issues in places like Safari.

**Comment by jonathontoon** [comment]
Deploying in Master now.
