### ISSUE TITLE
Codebase Style Questions.

### ISSUE THREAD

**Issue by jaspertravers** [jonathontoon/manifest#141]
I'm currently playing around with a vanilla `html`/`js` project and getting started by mostly replicating the functionality here. Thank you for the great example.

I see that you use parcel, scss and follow the PWA guidelines on mdn. But I don't see in any of those technology choices guidelines that lead to the codebase here.

Is there a style that this code base follows? Or some formalized practice? For example: is it standard to handle mouse/touch events through `document` in the style of this codebase? (add depending on target, remove on `mouseup`) I interpret this style as a sort of "switch-on-target" global handler.

In my replication I added the handlers to the memos themselves and immediately saw why you don't do that: I can drag the mouse too quickly and lose the `mousemove` handler.

I ask because every mature framework has its own formalized best practices and extensive documentation, but I can't seem to find that for modern `html`/`js`, at least in terms of the way that handlers are organized here with addition/removal and universally targeting `document`. It's also clear that this is an extremely polished project and I would like to tap into that knowledge if possible. At the very least I still have your code to follow.

Again, thank you, it's been a fun learning experience thus far,

Jasper

PS: Feel free to close this issue immediately, apologies in advance if this is not the right medium for the question.

**Comment by jonathontoon** [comment]
No worries for reaching out. 

As it's been awhile since I started this project I've come across some better baseline frameworks or project structures that you might enjoy looking at. [Here](https://github.com/wiledal/vanilla-bean) and [here](https://gomakethings.com/how-i-structure-my-vanilla-js-projects/).

Otherwise regarding "coding-style" there isn't really a driving principle for this project, other than say my general preference for what makes code readable (along with say my .eslintrc config). You're right in your observations of Parcel, SASS and the .webmanifest config, they are simply means to an end. 

When it comes to how I've used event handlers it's really just using what made most sense for the interactions I wanted. For example attaching certain events to the `document` made sense as mouse movements may become distorted or lose focus due to certain child elements.

All in all I'm afraid you won't really find what you might be searching for because really this project was intentionally done in my own personal way (not based on any intense reasoning) because I was frustrated with how much red tape and debate come from larger JavaScript frameworks. Also for a project like this it would be overkill in my opinion.

I'm happy you can use my example to learn, I'm glad it's simple enough for people to read! I would ask though that any replications you make and plan to release are inline with the [GPL 2.0 license](https://github.com/jonathontoon/manifest/blob/master/LICENSE) which has been set for this project.

Always happy to answer questions on [Twitter](https://twitter.com/jonathontoon).

**Comment by jaspertravers** [comment]
Those are great resources, thank you!

The rest of what your write makes sense, and I appreciate you sharing them.

I'm doing this just for practice with event listeners and dynamically created dom elements with no intention to release anything. Should that change I'll heed your license.

Thanks again!
