### ISSUE TITLE
Minimize & Header for Pinboard

### ISSUE THREAD

**Issue by thedhanawada** [jonathontoon/manifest#97]
With numerous pinboards around, minimize option would really be helpful and a header to identify the type of pinboard.

**Comment by jonathontoon** [comment]
Hi @thedhanawada thanks for the suggestions!

I feel like an option to minimize a memo diminishes the emphasis on positioning and organizing objects on a grid. Regarding a header, I'm not quite sure I understand this. Could you perhaps elaborate on how it would be used?

**Comment by thedhanawada** [comment]
Currently, the complete carpet space of the memo could be used to basically write anything up. A header is just how it sounds like, a header for every memo. I was more thinking about a header because if there was a possibility of a memo, a header would be a way to identify what each memo is when being minimized.

**Comment by alvianx** [comment]
Hi, this is my preview about the idea of minimize and header, also I think sticky features would be great too.

![Screenshot_2020-02-03 Manifest](https://user-images.githubusercontent.com/16168046/73616540-4b68c080-4647-11ea-85cb-739efd81f7ee.png)

**Comment by this-fifo** [comment]
personally, if I were to think of a way to support that, I'd suggest supporting workspaces to organize numerous pinboards instead of minimizing them, the workspace could represent the type

these could be implemented by something like a urlparam which could be used as the workspace key to differentiate between which local storage objects to display in the grid _(although I haven't poked at the code yet so not sure how hard it would be)_

looking at this again, I notice my idea is basically a different feature on its own and there's no reason why the app could not have both, so I created a new issue to avoid getting in the way of this one #118

**Comment by jonathontoon** [comment]
@alvianx thanks for the example!

After giving this all some time to stew a bit, I still am of the same opinion that this feature adds in complexity that doesn't really benefit the experience in any major way.

While it seems the sentiment is wanting more density and to hide memos, it's kind of the antithesis of having the grid and forcing people to organize ideas in a constrained way.

I understand I am being a little pedantic but I am quite concerned with keeping Manifest lean and it's features to an absolute minimum, where at all possible.
